# need at least one obj file to build for Kbuild
obj-y							+= dummy.o
obj-y							+= ether8139.o
# Following are from gpxe and need a lot of help.
#obj-y							+= mii.o
#obj-y							+= r8169.o
#obj-y							+= e1000/
