#!/bin/ash

# known good.
hossinMAC=00241d1054e1
c89MAC=001e67652333
c99MAC=001e67c2f479
altdraMAC=525400b0c2ec
qemuMAC=525400123456
tower1MAC=00032d196d88
tower2MAC=00032d196ddd
tower3MAC=00032d196d46
tower4MAC=00032d196db0
tower5MAC=00032d196daa

if [ "$MAC" = "$qemuMAC" ]
then
    echo "Welcome to QEMU!"
fi

# the tower of ... tower
# all defaults are fine.
if [ "$MAC" = "$tower1MAC" ]
then
    me=10.0.2.15
fi
if [ "$MAC" = "$tower2MAC" ]
then
    me=10.0.2.16
fi
if [ "$MAC" = "$tower3MAC" ]
then
    me=10.0.2.17
fi
if [ "$MAC" = "$tower4MAC" ]
then
    me=10.0.2.18
fi
if [ "$MAC" = "$tower5MAC" ]
then
    me=10.0.2.19
fi

if [ "$MAC" = "$c89MAC" ]
then
	# c89's config.  use c96 for eth0 (.196).
	# $ cat /9/net/ipifc/clone (get e.g. 2)
	# $ echo "add 169.229.49.196 255.255.255.0" > /9/net/ipifc/2/ctl
	me=169.229.49.196
	mask=255.255.255.0
	remote=169.229.49.0
	route=169.229.49.1
	# the i350 NIC that is plugged in is the first NIC
	NIC="0"
fi

if [ "$MAC" = "$c99MAC" ]
then
	# c99's config.  use c95 for eth0 (.195).
	# $ cat /9/net/ipifc/clone (get e.g. 2)
	# $ echo "add 169.229.49.195 255.255.255.0" > /9/net/ipifc/2/ctl
	me=169.229.49.195
	mask=255.255.255.0
	remote=169.229.49.0
	route=169.229.49.1
	# the i350 NIC that is plugged in is the first NIC
	NIC="0"
fi

if [ "$MAC" = "$altdraMAC" ]
then
	# yuzhu's soda hall bridged vm
	me=128.32.37.37
	mask=255.255.255.0
	remote=128.32.37.0
	route=128.32.37.1
fi

if [ "$MAC" = "$hossinMAC" ]
then
	# brho's soda hall desktop
	me=128.32.37.46
	mask=255.255.255.0
	remote=128.32.37.0
	route=128.32.37.1
fi
