#!/bin/ash
#bind -a '#I' /net
#bind -a '#l0' /net
#cat /9/net/ipifc/clone
## bind the ether0 to it
#myecho /9/net/ipifc/0/ctl 'bind ether /net/ether0'
#exit

# ifconfig it

export cputype=amd64
export objtype=$cputype
export service=cpu
export authid=bootes
export rootdir=/root
export rootspec=''
export rootsrv=boot

#authentication='nvram=/boot/adm/nvram auth/factotum -sfactotum -S'      # -a ...
# test xyzip=(0 0 0 104.9.33)
# test fsaddr='tcp!135.$xyzip(4)^!564'
# (me network server server-addr
# wrong addresses.
me=10.0.2.15
net=10.0.2.0
vm=10.0.2.1
rote=10.0.2.0

#
# Post the read-only filesystem in #s/$beetroot
# and mount it on /boot so the commands in /boot/$cputype/bin
# are available to create the namespace (namespaces like to
# mount #s/boot on / and that should not be the read-only
# filesystem).
# Must set hostowner to be that of the owner of the nvram file
# before paqfs starts otherwise factotum will not be able to
# open it.
#
#/boot/echo -n sys > '#c/hostowner'
#/boot/paqfs -p -S $beetroot -m /boot -q /boot/$beetroot
#cd /boot/$cputype/bin
bind '#c' /dev
#bind '#d' /fd
#bind -c '#e' /env
bind '#p' /proc
bind -c '#s' /srv

#
# Configure the networks.
#
bind -a '#I' /net
bind -a '#l0' /net

# note: dhcp is possible, just not done yet.
#get an instance of a network stack
#i=`{sed '' /9/net/ipifc/clone}
#ah, busybox, you suck.
#i=`cat /net/ipifc/clone`
cat /9/net/ipifc/clone
i=0
# bind the ether0 to it
myecho  /9/net/ipifc/$i/ctl "bind ether /net/ether0 "
# ifconfig it
myecho  /9/net/ipifc/$i/ctl "add $me $net $vm"
myecho /9/net/iproute "add 0 0 $route"
echo I am $me, default route $route

#i=`cat /net/ipifc/clone`
cat /9/net/ipifc/clone
i=1
myecho  /9/net/ipifc/$i/ctl "bind loopback /dev/null "
myecho  /9/net/ipifc/$i/ctl "add 127.0.0.1 255.0.0.0 127.0.0.0 "
