#!/bin/sh
# N.B. Preserve blank line we match against so this is idempotent.
sed -i '/^#include/,/^$/c\
#include <vfs.h>\
#include <slab.h>\
#include <kmalloc.h>\
#include <kref.h>\
#include <string.h>\
#include <stdio.h>\
#include <assert.h>\
#include <error.h>\
#include <cpio.h>\
#include <pmap.h>\
#include <smp.h>\
#include <ip.h>\
' $1
