obj-y						+= acpi.o
obj-y						+= alarm.o
obj-y						+= coreboot.o
obj-y						+= cons.o
obj-y						+= ether.o
obj-y						+= mnt.o
#obj-y						+= pci.o
obj-y						+= pipe.o
obj-y						+= proc.o
obj-y						+= root.o
obj-y						+= srv.o

# VM support. Optional.
obj-$(CONFIG_VM)				+= vm.o
