#define MEMP_NUM_SYS_TIMEOUT 10
#define NO_SYS 0
#define LWIP_SOCKET 1
#define LWIP_NETCONN 1
#define LWIP_TCP 1
#define SYS_LIGHTWEIGHT_PROT 1
#define LWIP_DHCP 1

#define TCP_SND_BUF 1096
//#define MEMP_NUM_TCP_SEG 32
 
#define ETHARP_DEBUG LWIP_DBG_ON
#define NETIF_DEBUG LWIP_DBG_ON
#define PBUF_DEBUG LWIP_DBG_ON
#define INET_DEBUG LWIP_DBG_ON
#define IP_DEBUG LWIP_DBG_ON
#define RAW_DEBUG LWIP_DBG_ON
#define UDP_DEBUG LWIP_DBG_ON

#define LWIP_DEBUG 1
