#!/bin/bash
export ARCH=x86
rm -f obj/tests/vmm/vmrunkernel kern/kfs/bin/vmrunkernel && make tests && make fill-kfs &&make  && sudo cp obj/kern/akaros-kernel /var/lib/tftpboot/akaros \
	&& echo "OK" && exit


#	&& sudo service isc-dhcp-server restart 
echo " IT WENT WRONG"

